### ISSUE TITLE
引入g2出错

### ISSUE THREAD

**Issue by LeslieTsui** [antvis/g2#1290]
import G2 from '@antv/g2';

Users/apple/Desktop/vscode/antv/g2.js:1
(function (exports, require, module, __filename, __dirname) { import G2 from '@antv/g2';
                                                                     ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

[Done] exited with code=1 in 0.106 seconds

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hellwen** [comment]
me to

**Comment by marsoln** [comment]
我也遇到了这个问题，经查看发现是之前在使用的时候，只安装了 @antv/data-set，没有安装 @antv/g2，但是之前的版本因为有依赖关系所以会自动安装 g2 的包，现在没有了，所以出现了这个错误。你可以查看一下 node_modules 下的 @antv 文件夹内有没有 g2 的包，如果没有，那么你只需要手动 `npm i @antv/g2` 然后就可以正常使用了。
