### ISSUE TITLE
react import g2 document is not defined

### ISSUE THREAD

**Issue by cunde** [antvis/g2#20]
(function (exports, require, module, __filename, __dirname) { !function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?define("G2",[],e):"object"==typeof exports?exports.G2=e():t.G2=e()}(this,function(){return function(t){function e(r){if(n[r])return n[r].exports;var i=n[r]={exports:{},id:r,loaded:!1};return t[r].call(i.exports,i,i.exports,e),i.loaded=!0,i.exports}var n={};return e.m=t,e.c=n,e.p="",e(0)}(function(t){for(var e in t)if(Object.prototype.hasOwnProperty.call(t,e))switch(typeof t[e]){case"function":break;case"object":t[e]=function(e){var n=e.slice(1),r=t[e[0]];return function(t,e,i){r.apply(this,[t,e,i].concat(n))}}(t[e]);break;default:t[e]=t[t[e]]}return t}([function(t,e,n){"use strict";var r={};r.Chart=n(307),r.Util=n(1),r.Global=n(5),r.Stat=n(19),r.Stat.map=n(216),r.Stat.tree=n(221),r.Stat.treemap=n(224),n(214),r.Scale=n(80),r.Shape=n(102),r.Frame=n(2),r.Theme=n(47),

ReferenceError: document is not defined
[1]     at /Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:1:6745
[1]     at Object.<anonymous (/Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:1:6795)
[1]     at e (/Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:1:319)
[1]     at Object.r (/Users/zoucunde/Code/kepler/dashbord/node_modules/g2/index.js:1:17168)
[1]     at e (/Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:1:319)
[1]     at Object.<anonymous> (/Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:1:19042)
[1]     at e (/Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:1:319)
[1]     at Object.<anonymous> (/Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:4:19805)
[1]     at e (/Users/cunde/Code/kepler/dashbord/node_modules/g2/index.js:1:319)
[1]     at Object.<anonymous>

**Comment by dxq613** [comment]
@jaredleechn 看一下

**Comment by jaredleechn** [comment]
g2 里面用了 document 变量？

**Comment by simaQ** [comment]
@jaredleechn 用到了

**Comment by jaredleechn** [comment]
这里应该是没有使用 g2-react，看起来像是直接在 react 使用了 g2，有更详细的项目信息么？

@cunde

**Comment by HaveF** [comment]
我也遇到了类似的情况，甚至都没有开始使用g2-react，只是想试试
```js
import createG2 from 'g2-react';
import { Stat } from 'g2';
```
然后就出错了

**Comment by dxq613** [comment]
移到g2-react项目讨论

**Comment by songjinzhou** [comment]
> 我也遇到了类似的情况，甚至都没有开始使用g2-react，只是想试试
> 
> ```js
> import createG2 from 'g2-react';
> import { Stat } from 'g2';
> ```
> 
> 然后就出错了
我也遇到了同样的问题，你是怎么解决的

**Comment by adhope** [comment]
@HaveF 了解了 就是从那里找来了
