### ISSUE TITLE
最新版本下TypeScript会产生：export 'angleTo' (imported as 'vec2') was not found in 'gl-matrix/vec2

### ISSUE THREAD

**Issue by cipchk** [antvis/G2#2326]
@dengfuping @hustcc 以下是完整日志，有关更多细节请见 [azure pipelines](https://dev.azure.com/ng-alain/delon/_build/results?buildId=44&view=logs&j=12ba5274-01f2-58f4-862e-1c6d6ded1764&t=3a56c4ea-20bb-51b8-1db9-a7b2b6bf8129)。

> 这里有[一份](https://dev.azure.com/ng-alain/delon/_build/results?buildId=41&view=logs&j=8cd93bc0-71e1-511b-b3fe-5b5711bf4f27&t=30c981be-7518-5654-ec2d-5d59fb481b12)半个小时前相同代码，但是**成功**的并没有以下错误信息，我不确定是否是g2正在升级哪一份依赖包引起的。

```
2020-04-16T06:18:38.9352831Z ERROR in ../node_modules/@antv/matrix-util/esm/vec2.js 16:0-12
2020-04-16T06:18:38.9353414Z "export 'angleTo' (imported as 'vec2') was not found in 'gl-matrix/vec2'
2020-04-16T06:18:38.9353992Z     at HarmonyImportSpecifierDependency._getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
2020-04-16T06:18:38.9354587Z     at HarmonyImportSpecifierDependency.getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
2020-04-16T06:18:38.9355129Z     at Compilation.reportDependencyErrorsAndWarnings (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1463:22)
2020-04-16T06:18:38.9355537Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1258:10
2020-04-16T06:18:38.9356023Z     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
2020-04-16T06:18:38.9356577Z     at AsyncSeriesHook.lazyCompileHook (/home/vsts/work/1/s/node_modules/tapable/lib/Hook.js:154:20)
2020-04-16T06:18:38.9357161Z     at Compilation.finish (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1253:28)
2020-04-16T06:18:38.9357544Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compiler.js:672:17
2020-04-16T06:18:38.9357949Z     at _done (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
2020-04-16T06:18:38.9358446Z     at eval (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
2020-04-16T06:18:38.9358871Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1185:12
2020-04-16T06:18:38.9359209Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1097:9
2020-04-16T06:18:38.9359561Z     at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-04-16T06:18:38.9360101Z  @ ../node_modules/@antv/matrix-util/esm/index.js
2020-04-16T06:18:38.9360765Z  @ ../node_modules/@antv/g2/esm/util/transform.js
2020-04-16T06:18:38.9361016Z  @ ../node_modules/@antv/g2/esm/index.js
2020-04-16T06:18:38.9361229Z  @ ./chart/bar/bar.component.ts
2020-04-16T06:18:38.9361434Z  @ ./chart/bar/bar.spec.ts
2020-04-16T06:18:38.9361614Z  @ . sync \.spec\.ts$
2020-04-16T06:18:38.9361787Z  @ ./test.ts
2020-04-16T06:18:38.9362232Z ERROR in ../node_modules/@antv/matrix-util/esm/vec2.js 13:0-14
2020-04-16T06:18:38.9362736Z "export 'direction' (imported as 'vec2') was not found in 'gl-matrix/vec2'
2020-04-16T06:18:38.9363193Z     at HarmonyImportSpecifierDependency._getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
2020-04-16T06:18:38.9363779Z     at HarmonyImportSpecifierDependency.getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
2020-04-16T06:18:38.9364318Z     at Compilation.reportDependencyErrorsAndWarnings (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1463:22)
2020-04-16T06:18:38.9364726Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1258:10
2020-04-16T06:18:38.9365193Z     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
2020-04-16T06:18:38.9365691Z     at AsyncSeriesHook.lazyCompileHook (/home/vsts/work/1/s/node_modules/tapable/lib/Hook.js:154:20)
2020-04-16T06:18:38.9366093Z     at Compilation.finish (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1253:28)
2020-04-16T06:18:38.9366469Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compiler.js:672:17
2020-04-16T06:18:38.9366873Z     at _done (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
2020-04-16T06:18:38.9367504Z     at eval (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
2020-04-16T06:18:38.9367930Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1185:12
2020-04-16T06:18:38.9368273Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1097:9
2020-04-16T06:18:38.9368619Z     at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-04-16T06:18:38.9369101Z  @ ../node_modules/@antv/matrix-util/esm/index.js
2020-04-16T06:18:38.9369376Z  @ ../node_modules/@antv/g2/esm/util/transform.js
2020-04-16T06:18:38.9369613Z  @ ../node_modules/@antv/g2/esm/index.js
2020-04-16T06:18:38.9369838Z  @ ./chart/bar/bar.component.ts
2020-04-16T06:18:38.9370032Z  @ ./chart/bar/bar.spec.ts
2020-04-16T06:18:38.9370226Z  @ . sync \.spec\.ts$
2020-04-16T06:18:38.9370400Z  @ ./test.ts
2020-04-16T06:18:38.9370797Z ERROR in ../node_modules/@antv/matrix-util/esm/vec2.js 18:27-41
2020-04-16T06:18:38.9371298Z "export 'direction' (imported as 'vec2') was not found in 'gl-matrix/vec2'
2020-04-16T06:18:38.9371752Z     at HarmonyImportSpecifierDependency._getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
2020-04-16T06:18:38.9372341Z     at HarmonyImportSpecifierDependency.getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
2020-04-16T06:18:38.9372876Z     at Compilation.reportDependencyErrorsAndWarnings (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1463:22)
2020-04-16T06:18:38.9373278Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1258:10
2020-04-16T06:18:38.9373742Z     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
2020-04-16T06:18:38.9374227Z     at AsyncSeriesHook.lazyCompileHook (/home/vsts/work/1/s/node_modules/tapable/lib/Hook.js:154:20)
2020-04-16T06:18:38.9374647Z     at Compilation.finish (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1253:28)
2020-04-16T06:18:38.9375021Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compiler.js:672:17
2020-04-16T06:18:38.9375545Z     at _done (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
2020-04-16T06:18:38.9376043Z     at eval (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
2020-04-16T06:18:38.9376455Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1185:12
2020-04-16T06:18:38.9376807Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1097:9
2020-04-16T06:18:38.9377153Z     at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-04-16T06:18:38.9377636Z  @ ../node_modules/@antv/matrix-util/esm/index.js
2020-04-16T06:18:38.9377910Z  @ ../node_modules/@antv/g2/esm/util/transform.js
2020-04-16T06:18:38.9378153Z  @ ../node_modules/@antv/g2/esm/index.js
2020-04-16T06:18:38.9378377Z  @ ./chart/bar/bar.component.ts
2020-04-16T06:18:38.9378571Z  @ ./chart/bar/bar.spec.ts
2020-04-16T06:18:38.9378767Z  @ . sync \.spec\.ts$
2020-04-16T06:18:38.9378927Z  @ ./test.ts
2020-04-16T06:18:38.9379339Z ERROR in ../node_modules/@antv/matrix-util/esm/mat3.js 17:0-14
2020-04-16T06:18:38.9379830Z "export 'transform' (imported as 'mat3') was not found in 'gl-matrix/mat3'
2020-04-16T06:18:38.9380285Z     at HarmonyImportSpecifierDependency._getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
2020-04-16T06:18:38.9380871Z     at HarmonyImportSpecifierDependency.getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
2020-04-16T06:18:38.9381389Z     at Compilation.reportDependencyErrorsAndWarnings (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1463:22)
2020-04-16T06:18:38.9381807Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1258:10
2020-04-16T06:18:38.9382363Z     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
2020-04-16T06:18:38.9382853Z     at AsyncSeriesHook.lazyCompileHook (/home/vsts/work/1/s/node_modules/tapable/lib/Hook.js:154:20)
2020-04-16T06:18:38.9383268Z     at Compilation.finish (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1253:28)
2020-04-16T06:18:38.9383629Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compiler.js:672:17
2020-04-16T06:18:38.9384046Z     at _done (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
2020-04-16T06:18:38.9384544Z     at eval (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
2020-04-16T06:18:38.9384954Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1185:12
2020-04-16T06:18:38.9385309Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1097:9
2020-04-16T06:18:38.9385640Z     at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-04-16T06:18:38.9386136Z  @ ../node_modules/@antv/matrix-util/esm/index.js
2020-04-16T06:18:38.9386418Z  @ ../node_modules/@antv/g2/esm/util/transform.js
2020-04-16T06:18:38.9386656Z  @ ../node_modules/@antv/g2/esm/index.js
2020-04-16T06:18:38.9386881Z  @ ./chart/bar/bar.component.ts
2020-04-16T06:18:38.9387075Z  @ ./chart/bar/bar.spec.ts
2020-04-16T06:18:38.9387268Z  @ . sync \.spec\.ts$
2020-04-16T06:18:38.9387429Z  @ ./test.ts
2020-04-16T06:18:38.9387833Z ERROR in ../node_modules/@antv/matrix-util/esm/vec2.js 30:0-13
2020-04-16T06:18:38.9388308Z "export 'vertical' (imported as 'vec2') was not found in 'gl-matrix/vec2'
2020-04-16T06:18:38.9388777Z     at HarmonyImportSpecifierDependency._getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
2020-04-16T06:18:38.9389368Z     at HarmonyImportSpecifierDependency.getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
2020-04-16T06:18:38.9389888Z     at Compilation.reportDependencyErrorsAndWarnings (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1463:22)
2020-04-16T06:18:38.9390393Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1258:10
2020-04-16T06:18:38.9390844Z     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
2020-04-16T06:18:38.9391341Z     at AsyncSeriesHook.lazyCompileHook (/home/vsts/work/1/s/node_modules/tapable/lib/Hook.js:154:20)
2020-04-16T06:18:38.9391754Z     at Compilation.finish (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1253:28)
2020-04-16T06:18:38.9392115Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compiler.js:672:17
2020-04-16T06:18:38.9392531Z     at _done (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
2020-04-16T06:18:38.9393021Z     at eval (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
2020-04-16T06:18:38.9393444Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1185:12
2020-04-16T06:18:38.9393798Z     at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1097:9
2020-04-16T06:18:38.9394129Z     at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-04-16T06:18:38.9394619Z  @ ../node_modules/@antv/matrix-util/esm/index.js
2020-04-16T06:18:38.9394878Z  @ ../node_modules/@antv/g2/esm/util/transform.js
2020-04-16T06:18:38.9395129Z  @ ../node_modules/@antv/g2/esm/index.js
2020-04-16T06:18:38.9395340Z  @ ./chart/bar/bar.component.ts
2020-04-16T06:18:38.9395547Z  @ ./chart/bar/bar.spec.ts
2020-04-16T06:18:38.9395741Z  @ . sync \.spec\.ts$
2020-04-16T06:18:38.9395902Z  @ ./test.ts
```

**Comment by cipchk** [comment]
我感觉应该是受 #2317 变更影响了吧。

**Comment by dxq613** [comment]
昨天为了解决 #2317 替换了 gl-matrix，我检查一下是否有上层用到的接口没有满足。

**Comment by dxq613** [comment]
已经回滚了，后面重新升级 gl-matrix
