### ISSUE TITLE
npm run demos运行失败

### ISSUE THREAD

**Issue by pslean** [antvis/g2#245]
操作步骤：
1. npm install
2. npm run demos
错误日志：
17 error Windows_NT 10.0.16299
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "demos"
19 error node v5.10.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error @antv/g2@3.0.1 demos: `$(npm bin)/electron ./demos/app.js`
22 error Exit status 1
23 error Failed at the @antv/g2@3.0.1 demos script '$(npm bin)/electron ./demos/app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the @antv/g2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     $(npm bin)/electron ./demos/app.js

**Comment by leungwensen** [comment]
要不你用 cnpm 先试一下？windows 环境我需要回家之后才能尝试

**Comment by pslean** [comment]
@leungwensen 我用了cnpm是一样的，本来我用的cnpm，后来换了npm还是一样报错

**Comment by leungwensen** [comment]
好的，那等我配置好 windows 环境之后修复一下

**Comment by pslean** [comment]
我试了下，直接执行package.json里面的命令是可以的，感觉很奇怪

**Comment by leungwensen** [comment]
https://github.com/antvis/g2/pull/253

基本上所有命令都能在 windows 上执行了。不过因为 `watch` 这样的挂起命令在 windows 下无法和其他命令并行执行，所以 `npm run dev` 事实上只会监听文件变化并且构建 `build/g2.js`。为了达到和 Unix 系一样的效果，额外增加了 `npm run win-dev` 命令，这个命令就相当于 `npm run watch & npm run demos-web`，只是命令行输出没有了颜色高亮。

**Comment by pslean** [comment]
在windows下用git shell就可以有高亮色了

**Comment by leungwensen** [comment]
没有高亮色的原因是，这个命令是用 shelljs 通过 子进程 实现的。

**Comment by leungwensen** [comment]
git shell 如果能直接跑 `npm run dev`，你也可以试一下

**Comment by pslean** [comment]
果然是没有高亮的，但是我npm run win-dev会报错。
ERROR in ./index.js
Module build failed: Error: Couldn't find preset "env" relative to directory "E:\\git\\g2"
    at E:\git\g2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (E:\git\g2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\git\g2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\git\g2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\git\g2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\git\g2\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\git\g2\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\git\g2\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\git\g2\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\git\g2\node_modules\babel-loader\lib\index.js:175:20)

**Comment by leungwensen** [comment]
你安装一下依赖，这个是 `babel` 找不到 `preset` 的出错提示。

**Comment by pslean** [comment]
终于OK了，非常感谢

**Comment by zouwenhuagit** [comment]
告诉我，你在哪里知道我的邮箱的，天天发我又看不懂
，请你告诉我





| |
zouwenhuascript
|
|
邮箱：zouwenhuascript@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 10:39，绝云 写道：

Closed #245.

**Comment by leungwensen** [comment]
@zouwenhuagit 可以提供一下从我们项目接收到的邮件信息（截图之类的）吗？我注意到您并没有 watch 咱们项目，也并没有在 contributors 列表里，照理说应该收不到邮件才对的。
