### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'onfinish')

### ISSUE THREAD

**Issue by pfdgithub** [antvis/G2#5777]
### 问题描述

@antv/g2@5.1.7

有时候，似乎是动画被打断时，会报异常，不稳定复现。
直接原因是 [这一行](https://github.com/antvis/G2/blob/v5/src/animation/morphing.ts#L185) 返回的 `animation` 是 null ，根本原因暂不清楚。

```
morphing.ts:188 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'onfinish')
    at oneToOne (morphing.ts:188:5)
    at morphing.ts:262:6
    at plot.ts:1526:15
    at plot.ts:992:35
    at selection.ts:395:14
    at _Selection.each (selection.ts:372:7)
    at _Selection.transition (selection.ts:394:17)
    at plot.ts:989:16
    at _Selection.call (selection.ts:410:5)
    at plot.ts:982:18
```

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
提供一下最小复现 demo，比如可以在 g2 官网运行的代码片段或者 codesand box
