### ISSUE TITLE
使用 Vite+pnpm+vue3 运行报错

### ISSUE THREAD

**Issue by dengsong666** [antvis/G2#6021]
### 问题描述

Failed to resolve entry for package "fmin". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/.pnpm/registry.npmmirror.com+esbuild@0.19.11/node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29443:17)
    at resolvePackageEntry (file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29440:5)
    at tryNodeResolve (file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29210:20)
    at Context.resolveId (file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:28978:28)
    at Object.resolveId (file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63984:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:68000:21
    at async file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:41435:34
    at async requestCallbacks.on-resolve (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:1374:22)
    at async handleRequest (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:732:11)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/registry.npmmirror.com+esbuild@0.19.11/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:41415:19)
    at handlePlugins (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:1293:21)
    at buildOrContextImpl (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:979:5)
    at Object.buildOrContext (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:788:5)
    at E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:2223:68  
    at new Promise (<anonymous>)
    at Object.context (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:2223:27)
    at Object.context (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:2048:58)
    at prepareEsbuildOptimizerRun (file:///E:/Code/vue3/stock/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.11_@types+node@20.9.4_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:65774:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/.pnpm/registry.npmmirror.com+@antv+g2@5.1.14/node_modules/@antv/g2/esm/data/utils/venn/layout.js:1:84:       
      1 │ import { bisect, conjugateGradient, nelderMead, norm2, scale, zeros, zerosM, } from 'fmin';
        ╵                                                                                     ~~~~~~

 ERROR  22:17:24 [vite] error while updating dependencies:                                                          22:17:24  
Error: Build failed with 1 error:
node_modules/.pnpm/registry.npmmirror.com+esbuild@0.19.11/node_modules/esbuild/lib/main.js:1374:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "fmin". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:1651:15)
    at E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:1059:25  
    at E:\Code\vue3\stock\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.19.11\node_modules\esbuild\lib\main.js:1527:9   
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
看起来像是 fmin 包太老了~
