### ISSUE TITLE
3.2.8版本安装依赖时报错

### ISSUE THREAD

**Issue by wupeiwen** [antvis/g2#926]
* **G2 Version**: 3.2.8
* **Platform**: win10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

> Couldn't find package "@antv/adjust@~0.0.7" required by "@antv/g2@^3.2.8" on the "npm"

yarn install v1.7.0
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "@antv/adjust@~0.0.7" required by "@antv/g2@^3.2.8" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@antv/scale@~0.0.9" required by "@antv/g2@^3.2.8" on the "npm" registry.
    at MessageError.ExtendableBuiltin (D:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (D:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (D:\Program Files (x86)\Yarn\lib\cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (D:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at D:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "@antv/gl-matrix@^2.7.1" required by "@antv/util@~1.2.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (D:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (D:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (D:\Program Files (x86)\Yarn\lib\cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (D:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at D:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "@antv/gl-matrix@~2.7.1" required by "@antv/g@~3.2.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (D:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (D:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (D:\Program Files (x86)\Yarn\lib\cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (D:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at D:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by leungwensen** [comment]
没有重现，要不再试一下？这个包是存在的 https://www.npmjs.com/package/@antv/adjust/v/0.0.7
